### ISSUE TITLE
'sum' not working with somewhat irregular shapes (census blocks)

### ISSUE THREAD

**Issue by wilsaj** [Turfjs/turf-aggregate#2]
It looks like the fix is already in the works, but just want to make sure it gets brought up.

I was trying to use turf-aggregate and it was not quite working (failing to correctly sum amongst census blocks), and I traced it down to the turf-inside version within turf-sum within turf-aggregate being a bit behind (0.1.4).

Directly linking to turf-aggregate to the the current github version of turf-sum works, so It looks like this will sort it self out when a new release of turf-sum is cut, and turf-aggregate's dependency is bumped to that version.

**Comment by tmcw** [comment]
Closing; becomes turf-combine
